### ISSUE TITLE
Arguments not being passed to perf

### ISSUE THREAD

**Issue by mrbojangles3** [perftool-incubator/tool-kernel#12]
With this snip of a tool-params file:
``` 
 { "tool": "kernel",
    "params": [{"arg":"subtools","val":"perf"}, { "arg": "record-opts", "val": "--freq=99 --namespaces --all-cgroups -e net:* -e qdisk:* -e tcp:*"} ] }
```
The only arg that makes it to the `kerneltools-start-stderrout.txt` is 
```
<snip>
setting subtools=perf
setting record_opts=--freq=99
Starting perf record
going to run /usr/bin/perf record -a --freq=99
<snip>
```
It seems there is an issue with getopt.

**Comment by k-rister** [comment]
Looking at the getopt parser in kerneltools-start I see a fairly unremarkable bit of code:

**Comment by k-rister** [comment]
Looking at the getopt parser in kerneltools-start I see a fairly unremarkable bit of code:

https://github.com/perftool-incubator/tool-kernel/blob/master/kerneltools-start#L22-L67

This is pretty standard but its not going to handle an option like `record-opts` as it is being used if the caller is not properly encapsulating the entire value inside a quoted string properly...something like:

```
<stuff> ... --record-opts "--freq=99 --namespaces --all-cgroups -e net:* -e qdisk:* -e tcp:*"
```

So we need to make sure that is happening.  I suspect that is occuring somewhere in https://github.com/perftool-incubator/rickshaw/blob/master/rickshaw-run

**Comment by atheurer** [comment]
I believe I have a solution for this.  We just need to build a bash array for the arguments and pass this array when calling to tool.  Patches coming soon.

**Comment by mrbojangles3** [comment]
from `kernel-tools-start-stderrout.txt`
```
args:
[--subtools]
[perf]
[--record-opts]
[--freq=99]
[--namespaces]
[--all-cgroups]
[-e]
[net:*]
[-e]
[tcp:*]
<skip output of mount>
Processing arguments
arg: [--subtools]  val: [perf]
setting subtools=perf
arg: [--record-opts]  val: [--freq=99]
setting record_opts=--freq=99
arg: [--]  val: [net:*]
Starting perf record
Going to run /usr/bin/perf record -a --freq=99
perf pid is 1117330
[ perf record: Woken up 138 times to write data ]
[ perf record: Captured and wrote 47.686 MB perf.data (429595 samples) ]
```
confirmed via `perf report --header-only`
`# cmdline : /usr/bin/perf record -a --freq=99`

```

**Comment by atheurer** [comment]
I believe you are still missing updates from engine and rickshaw

**Comment by atheurer** [comment]
This is what I see (I have slightly different tool-params):


```
args:
[--subtools]
[perf]
[--record-opts]
[--freq=99 --namespaces --all-cgroups -e net:*]

Processing arguments
arg: [--subtools]  val: [perf]
setting subtools=perf
arg: [--record-opts]  val: [--freq=99 --namespaces --all-cgroups -e net:*]
setting record_opts=--freq=99 --namespaces --all-cgroups -e net:*
arg: [--]  val: []
Starting perf record
Going to run /usr/bin/perf record -a --freq=99 --namespaces --all-cgroups -e net:*
perf pid is 300795
```

It seems like you do not have the rickshaw-run update, at least from the behavior.

**Comment by atheurer** [comment]
required fixes include:

https://github.com/perftool-incubator/rickshaw/pull/225
https://github.com/perftool-incubator/engine/pull/6
https://github.com/perftool-incubator/tool-kernel/pull/13

**Comment by mrbojangles3** [comment]
those PRs worked.
